### ISSUE TITLE
Requires Botania 1.10-359 but 1.10-358 is latest on Curse?

### ISSUE THREAD

**Issue by nephatrine** [p455w0rd/OrechidEndium#1]
This requires a newer Botania version to run than is available on CurseForge. Can't find that version available for d/l anywhere else either.

**Comment by nephatrine** [comment]
Hmm maybe nevermind. It looks like you uploaded a newer version that going by changelog fixes this but its under Minecraft 1.11.2 instead of 1.12.2 on the mod page.

**Comment by p455w0rd** [comment]
lol..derp..its fixed now
